create or replace view HYPERLIQUID_DB.STAKING_SCHEMA.VIEW_VALIDATOR_RANKING(
	VALIDATOR_ADDRESS,
	CURRENT_STAKE,
	VALIDATOR_ACTIVE,
	COMMISSION_RATE,
	SNAPSHOT_DATE
) as
SELECT

    f.value:name::STRING AS VALIDATOR_ADDRESS,
    f.value:stake::FLOAT AS CURRENT_STAKE,
    f.value:isActive::STRING AS VALIDATOR_ACTIVE,
    f.value:commission::FLOAT AS COMMISSION_RATE,-- Ha az API ad nevet
    SNAPSHOT_DATE
FROM HYPERLIQUID_DB.STAKING_SCHEMA.RAW_STAKING_METRICS,
LATERAL FLATTEN(input => currentValidatorStakes) f;
