create or replace view HYPERLIQUID_DB.STAKING_SCHEMA.VIEW_VALIDATOR_DAILY_PERFORMANCE(
	REPORT_DATE,
	VALIDATOR_ADDRESS,
	DAILY_STAKE,
	DAILY_REWARDS
) as
SELECT 
    f.value:date::DATE AS REPORT_DATE,
    f.value:name::STRING AS VALIDATOR_ADDRESS,
    f.value:stake::FLOAT AS DAILY_STAKE,
    f.value:rewards::FLOAT AS DAILY_REWARDS
FROM HYPERLIQUID_DB.STAKING_SCHEMA.RAW_STAKING_METRICS,
LATERAL FLATTEN(input => validatorDailyData) f;
